import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono } from "next/font/google";
import { BackgroundImage } from "@/components/background-image";
import { axiforma } from "@/fonts";

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${axiforma.variable} ${geistMono.variable} antialiased bg-black font-sans`}
                style={{
                    fontFamily:
                        "Axiforma, var(--font-axiforma), system-ui, sans-serif",
                }}
            >
                <BackgroundImage />
                {children}
            </body>
        </html>
    );
}
